version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000" # Adjust ports as needed
    environment:
      - PORT=3000
    networks:
      - app-network
  users:
    build: ./users
    ports:
      - "3000:3000" # Adjust ports as needed
    environment:
      - PORT=3000
    networks:
      - app-network
  payments:
    build: ./payments
    ports:
      - "3000:3000" # Adjust ports as needed
    environment:
      - PORT=3000
    networks:
      - app-network
  file-manager:
    build: ./file-manager
    ports:
      - "3000:3000" # Adjust ports as needed
    environment:
      - PORT=3000
    networks:
      - app-network
  email-service:
    build: ./email-service
    ports:
      - "3000:3000" # Adjust ports as needed
    environment:
      - PORT=3000
    networks:
      - app-network
  groceries:
    build: ./groceries
    ports:
      - "3000:3000" # Adjust ports as needed
    environment:
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
